from random import randrange

import blazer
from blazer.hpc.mpi.primitives import rank

with blazer.variable() as vars:

    def watch(var):
        print("watch[rank {}] var {}".format(rank, var))

    vars.watch("rank1", watch)
    vars.watch("rank2", watch)

    rv = randrange(10)

    vars["rank" + str(rank)] = [
        {"key": "rank" + str(rank) + " v:" + str(randrange(10))},
        randrange(10),
        randrange(10),
        randrange(10),
    ]

    blazer.print(vars.vars)
    if rank == 1:
        # Print some data generated by rank2
        print("Rank 1: Data from Rank 2: ", vars["rank2"])
        # Print some data generated by rank1
        print("Rank 1: Data from Rank 0: ", vars["rank0"])
